# Generated by Django 3.1.2 on 2021-02-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.CharField(max_length=1000, null=True)),
                ('description2', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('thumnail', models.ImageField(upload_to='documents/')),
            ],
        ),
    ]
